name: segproj
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - debugpy=1.8.17=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nvidia-ml-py=13.580.82=pyhd8ed1ab_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312h5253ce2_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=8_cp312
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.2=py312h4c3975b_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - amqp==5.3.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - app-model==0.4.0
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astropy==7.1.0
      - astropy-iers-data==0.2025.11.10.0.38.31
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.4.0
      - av==16.0.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bermuda==0.1.6
      - billiard==4.2.3
      - bleach==6.3.0
      - build==1.3.0
      - cachetools==6.2.2
      - cachey==0.2.1
      - celery==5.5.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.2.1
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - cloudpickle==3.1.2
      - colorful==0.5.8
      - connectorx==0.4.4
      - contourpy==1.3.3
      - coverage==7.12.0
      - crc32c==2.8
      - cryptography==46.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dask==2025.11.0
      - dataio==0.0.5
      - deepspeed==0.17.6
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - distlib==0.4.0
      - dm-tree==0.1.9
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - donfig==0.8.1.post1
      - einops==0.8.1
      - farama-notifications==0.0.4
      - fastapi==0.121.2
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.60.1
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - gymnasium==1.1.1
      - h11==0.16.0
      - h2==4.3.0
      - heapdict==1.0.1
      - hf-xet==1.2.0
      - hjson==3.1.0
      - hpack==4.1.0
      - hsluv==5.0.4
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==1.1.5
      - hydra-core==1.3.2
      - hyperframe==6.1.0
      - idna==3.11
      - imagecodecs==2025.11.11
      - imageio==2.37.2
      - imagesize==1.4.1
      - in-n-out==0.2.1
      - iniconfig==2.3.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipykernel==6.31.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - itk==5.4.5
      - itk-core==5.4.5
      - itk-filtering==5.4.5
      - itk-io==5.4.5
      - itk-numerics==5.4.5
      - itk-registration==5.4.5
      - itk-segmentation==5.4.5
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - lark==1.3.1
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - line-profiler==5.0.0
      - line-profiler-pycharm==1.2.0
      - linkify-it-py==2.0.3
      - llvmlite==0.45.1
      - locket==1.0.0
      - lz4==4.4.5
      - magicgui==0.10.1
      - makefun==1.16.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - memray==1.19.1
      - mistune==3.1.4
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - napari==0.6.6
      - napari-console==0.1.4
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.8
      - napari-svg==0.2.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - nibabel==5.3.2
      - ninja==1.13.0
      - noko==0.3.1
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - npe2==0.7.9
      - numba==0.62.1
      - numcodecs==0.16.5
      - numpy==2.3.5
      - numpydoc==1.9.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-dali-cuda130==1.52.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvcomp-cu13==5.0.0.6
      - nvidia-nvimgcodec-cu13==0.6.1.37
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvjpeg==13.0.1.86
      - nvidia-nvjpeg2k-cu13==0.9.1.47
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtiff-cu13==0.6.0.78
      - nvidia-nvtx-cu12==12.8.90
      - nvitop==1.5.3
      - nvtx==0.2.13
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-prometheus==0.59b0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.4
      - ormsgpack==1.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - partd==1.4.2
      - pillow==12.0.0
      - pint==0.25.2
      - pluggy==1.6.0
      - polars==1.28.1
      - pooch==1.8.2
      - portalocker==3.2.0
      - postgrest==2.24.0
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psygnal==0.15.0
      - py-cpuinfo==9.0.0
      - py-libnuma==1.2
      - py-spy==0.4.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyclesperanto==0.19.0
      - pyconify==0.2.1
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.41.5
      - pydensecrf2==1.1
      - pyerfa==2.0.1.5
      - pyjwt==2.10.1
      - pymongo==4.15.4
      - pyopengl==3.1.10
      - pyopenssl==25.3.0
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.17.1
      - pytest==8.4.2
      - pytest-order==1.3.0
      - pytest-testmon==2.1.3
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytorchvideo==0.1.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - ray==2.49.2
      - realtime==2.24.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.45.0
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starlette==0.49.3
      - storage3==2.24.0
      - strenum==0.4.15
      - supabase==2.19.0
      - supabase-auth==2.24.0
      - supabase-functions==2.24.0
      - superqt==0.7.6
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorstore==0.1.77
      - termcolor==3.2.0
      - terminado==0.18.1
      - textual==6.6.0
      - threadpoolctl==3.6.0
      - tifffile==2025.9.20
      - timm==1.0.20
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli-w==1.2.0
      - toolz==1.1.0
      - torch==2.9.1
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triangle==20250106
      - trino==0.336.0
      - triton==3.5.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - uc-micro-py==1.0.3
      - ujson==5.11.0
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vine==5.1.0
      - virtualenv==20.35.4
      - vispy==0.15.2
      - wandb==0.22.0
      - watchfiles==1.1.1
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - yacs==0.1.8
      - yarl==1.22.0
      - zarr==3.1.3
      - zstandard==0.25.0
prefix: /clusterfs/nvme/martinalvarez/miniforge3/envs/segproj
